name: CI
on:
  pull_request:
  push:

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-12
          # - windows-latest
        node_version:
          - 16
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6  # tag: v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561  # tag: v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies and build
        run: yarn

      - name: Build altenative architecture
        if: matrix.os == 'macos-latest'
        run: MINIDUMP_BUILD_ARCH=arm64 node build.js

      - name: Tests
        run: yarn test

      - name: Upload artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2  # tag: v2
        with:
          path: ./bin

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI ðŸš«
        run: echo skip ci
